@testable import GeminiHandle
import VaporTesting
import Testing

@Suite("App Tests")
struct GeminiHandleTests {
    @Test("Test GeminiClient configuration")
    func clientConfiguration() throws {
        let config = GeminiConfiguration(
            apiKey: "test-key",
            model: "gemini-2.0-flash",
            systemInstruction: "You are a helpful assistant."
        )

        let client = GeminiClient(configuration: config)

        #expect(client.model == "gemini-2.0-flash")
        #expect(client.apiKey == "test-key")
    }

    @Test("Test GeminiClientError descriptions")
    func errorDescriptions() {
        #expect(GeminiClientError.missingAPIKey.errorDescription == "GEMINI_API_KEY is not configured")
        #expect(GeminiClientError.emptyResponse.errorDescription == "Empty response from Gemini API")
        #expect(GeminiClientError.noCandidates.errorDescription == "No response candidates generated by Gemini")
        #expect(GeminiClientError.blocked(reason: "safety").errorDescription == "Request blocked by safety filters: safety")
    }

    @Test("Test GeminiChatMessage helpers")
    func chatMessageHelpers() {
        let userMsg = GeminiChatMessage.user("Hello")
        let assistantMsg = GeminiChatMessage.assistant("Hi there!")

        #expect(userMsg.role == "user")
        #expect(userMsg.text == "Hello")
        #expect(assistantMsg.role == "model")
        #expect(assistantMsg.text == "Hi there!")
    }

    @Test("Test GeminiContent helpers")
    func contentHelpers() {
        let userContent = GeminiContent.user("Hello")
        let modelContent = GeminiContent.model("Hi!")

        #expect(userContent.role == "user")
        #expect(userContent.parts.first?.text == "Hello")
        #expect(modelContent.role == "model")
        #expect(modelContent.parts.first?.text == "Hi!")
    }
}
