import Foundation

public struct GeminiAPIError: Codable, Sendable, Error {
    public let error: GeminiErrorDetail?

    public struct GeminiErrorDetail: Codable, Sendable {
        public let code: Int
        public let message: String
        public let status: String
    }
}

public enum GeminiClientError: Error, Sendable, LocalizedError {
    case missingAPIKey
    case emptyResponse
    case noCandidates
    case blocked(reason: String?)
    case apiError(code: Int, message: String)
    case invalidURL
    case streamingFailed

    public var errorDescription: String? {
        switch self {
        case .missingAPIKey:
            return "GEMINI_API_KEY is not configured"
        case .emptyResponse:
            return "Empty response from Gemini API"
        case .noCandidates:
            return "No response candidates generated by Gemini"
        case .blocked(let reason):
            return "Request blocked by safety filters: \(reason ?? "unknown")"
        case .apiError(let code, let message):
            return "Gemini API error (\(code)): \(message)"
        case .invalidURL:
            return "Invalid Gemini API URL"
        case .streamingFailed:
            return "Gemini streaming failed"
        }
    }
}
